<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{34467066-1969-4a23-bd22-a8eb1fd5af96}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[P_ControlBox(); // Run selected control box mode (virtual or real)]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>