<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{64fcf6ed-0c4f-4bc5-b41e-dc3380c209f6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	bActivateMotion : BOOL;
	fVelRef : LREAL;
	fPosRef: LREAL;
	fPosMeas :LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>